import Navigation from "@/components/navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title:  {
    template: "%s | meta",
    default: "Next Movies"
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
